// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_bNv4EKtyHO77pN0_ngJ1F-uPKNZXyRw',
    appId: '1:181224449896:web:b0b74251c6bfac8fd4d8dd',
    messagingSenderId: '181224449896',
    projectId: 'kelas-c-projek-676',
    authDomain: 'kelas-c-projek-676.firebaseapp.com',
    storageBucket: 'kelas-c-projek-676.appspot.com',
    measurementId: 'G-T893N1SEDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8W6ggI2k0rZWwizkMWCD2xoIl5Wod3eE',
    appId: '1:181224449896:android:eb215bfe071d8c33d4d8dd',
    messagingSenderId: '181224449896',
    projectId: 'kelas-c-projek-676',
    storageBucket: 'kelas-c-projek-676.appspot.com',
  );
}
