import 'package:flutter/material.dart';

class KontakScreen extends StatelessWidget {
  const KontakScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("kontak"),
      ),
      body: ListView(
        children: [
          Text("budi"),
          Text("budi"),
          Text("budi4"),
          Text("budi7"),
          Text("budi9"),
          Text("budi1"),
          Text("budi"),
          Text("budi4"),
          Text("budi1"),
          Text("budi"),
          Text("budi6"),
          Text("budi"),
          Text("budi4"),
          Text("budi7"),
          Text("budi9"),
          Text("budi1"),
          Text("budi"),
          Text("budi4"),
          Text("budi1"),
          Text("budi"),
          Text("budi6"),
          Text("budi"),
          Text("budi4"),
          Text("budi7"),
          Text("budi9"),
          Text("budi1"),
          Text("budi"),
          Text("budi4"),
          Text("budi1"),
          Text("budi"),
          Text("budi6"),
          Text("budi"),
          Text("budi4"),
          Text("budi7"),
          Text("budi9"),
          Text("budi1"),
          Text("budi"),
          Text("budi4"),
          Text("budi1"),
          Text("budi"),
          Text("budi6"),
          Text("budi"),
          Text("budi"),
          Text("budi"),
          Text("budi"),
          Text("budi"),
          Text("budi"),
          Text("budi"),
          Text("budi"),
          Text("budi1"),
          Text("budi4"),
          Text("budi"),
          Text("budi6"),
          Text("budi"),
          Text("budi7"),
          Text("budi"),
          Text("budi7"),
          Text("budi"),
          Text("budi"),
          Text("budi"),
        ],
      ),
    );
  }
}
